DATALOADER:
  TRAIN_X:
    #BATCH_SIZE: 32
    BATCH_SIZE: 128
#    SAMPLER: "RandomSampler"
  TEST:
    #BATCH_SIZE: 100
    #BATCH_SIZE: 13201
    BATCH_SIZE: 128
  NUM_WORKERS: 8
#  NUM_CLASS: 4000

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:  #for coop
  NAME: "sgd"
  LR: 0.0009  #0.002
  MAX_EPOCH: 200 #100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 0  #1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5 #1e-5

TRAIN:
  PRINT_FREQ: 100

MODEL:
  BACKBONE:
    NAME: "RN50"

TRAINER:
  COOP:
    CTX_INIT: "an item of a"

TRANSFORMER:
  EMBED_DIM: 100
  HIDDEN_UNIT: 50 #60 #90 #100 #150 #100 #50
  DROPOUT_RATE: 0.2  #0.2
  NUM_HEADS: 1
  MAX_LEN: 64 #77 #50  64for movie-book,77for food kitchen
  NUM_BLOCKS: 2
  LR: 0.001
  DEVICE: "cuda:0"  #"cuda:1"